/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppContentListWallet {
    'history': RouterHistory;
  }
  interface AppContentListWalletAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface AppListWallet {}
  interface AppListWalletAttributes extends StencilHTMLAttributes {}

  interface AppModal {
    'title': string;
    'visible': boolean;
  }
  interface AppModalAttributes extends StencilHTMLAttributes {
    'onCancel'?: (event: CustomEvent) => void;
    'onOk'?: (event: CustomEvent) => void;
    'title'?: string;
    'visible'?: boolean;
  }

  interface AppRoot {
    'history': RouterHistory;
  }
  interface AppRootAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppContentListWallet': Components.AppContentListWallet;
    'AppListWallet': Components.AppListWallet;
    'AppModal': Components.AppModal;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-content-list-wallet': Components.AppContentListWalletAttributes;
    'app-list-wallet': Components.AppListWalletAttributes;
    'app-modal': Components.AppModalAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppContentListWalletElement extends Components.AppContentListWallet, HTMLStencilElement {}
  var HTMLAppContentListWalletElement: {
    prototype: HTMLAppContentListWalletElement;
    new (): HTMLAppContentListWalletElement;
  };

  interface HTMLAppListWalletElement extends Components.AppListWallet, HTMLStencilElement {}
  var HTMLAppListWalletElement: {
    prototype: HTMLAppListWalletElement;
    new (): HTMLAppListWalletElement;
  };

  interface HTMLAppModalElement extends Components.AppModal, HTMLStencilElement {}
  var HTMLAppModalElement: {
    prototype: HTMLAppModalElement;
    new (): HTMLAppModalElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-content-list-wallet': HTMLAppContentListWalletElement
    'app-list-wallet': HTMLAppListWalletElement
    'app-modal': HTMLAppModalElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-content-list-wallet': HTMLAppContentListWalletElement;
    'app-list-wallet': HTMLAppListWalletElement;
    'app-modal': HTMLAppModalElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
